on:
  push:
    paths:
      - 'yarn.lock'
      - 'web/yarn.lock'

name: Check lockfiles
jobs:
  build:
    env:
      FVULS_BASE_URL: "https://rest.2119e7c929.vuls.biz"
      FVULS_SERVER_UUID: ${{ secrets.FVULS_SERVER_UUID }}
      FVULS_TOKEN: ${{ secrets.FVULS_TOKEN }}
    name: Upload lockfile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload web/yarn.lock
        uses: futurevuls/fvuls-lockfile-uploader@v1
        with:
          repoName: ${{ github.repository }}
          path: './yarn.lock'
